### ISSUE TITLE
Code changes already completed

### ISSUE THREAD

**Issue by toddwhitehead** [Microsoft/MCW-IoT-and-the-Smart-City#15]
Exercise 3 describes a series of code changes for the participant to make but the supplied code already has these changes made

https://github.com/Microsoft/MCW-IoT-for-business/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20IoT%20for%20business.md#exercise-3-create-bus-and-traffic-light-simulated-devices-and-add-alerts-and-filters

**Comment by akn9050** [comment]
confirmed same

**Comment by mrfalafel** [comment]
Code that was supposed to be entered by students has been commented out in the files. Students will only need to comment out Todo 1 to 4 in the lab exercises.
