### ISSUE TITLE
Storage adapter service returns 404 error

### ISSUE THREAD

**Issue by toddwhitehead** [Microsoft/MCW-IoT-and-the-Smart-City#16]
When follwoing the steps for running the storage adapter service (Task 4 at https://github.com/Microsoft/MCW-IoT-for-business/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20IoT%20for%20business.md#exercise-3-create-bus-and-traffic-light-simulated-devices-and-add-alerts-and-filters) when running in debug the browsing to /v1/status just returns a 404.

The service uses the kestrel server on port 9022 so I assume it doesn't matter what VS is using for IIS Express as this will vary between installations. Is there some additional setup that needs to be done?
The screen shot of the properties for the project only shows a portion of the screen so its difficult to tell if any other settings are made.

**Comment by akn9050** [comment]
hi @toddwhitehead we have to update App URL http://localhost/9022/ in properties>debug just below the environment variables and also need to update Launch Browser url with **http://localhost:9022/v1/status** Then it works. This is not mentioned in document.

**Comment by mrfalafel** [comment]
Please try in March update.
