### ISSUE TITLE
Storage adapter url env value missing

### ISSUE THREAD

**Issue by toddwhitehead** [Microsoft/MCW-IoT-and-the-Smart-City#17]
When setting up the Simulation Agent the screenshot partially shows an environment value for the url of the storage adapter service. This var isnt present in the solution and the screenshot below is truncated so it isnt clear what the value should be.

https://github.com/Microsoft/MCW-IoT-for-business/blob/master/Hands-on%20lab/images/Hands-onlabstep-by-step-IoTforbusinessimages/media/image43.png

**Comment by mrfalafel** [comment]
Please try in March update.
