### ISSUE TITLE
Issue while running Webservice project 

### ISSUE THREAD

**Issue by akn9050** [Microsoft/MCW-IoT-and-the-Smart-City#19]
Facing issue in [Exercise 3 task 5](https://github.com/Microsoft/MCW-IoT-for-business/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20IoT%20for%20business.md#task-5-run-the-simulator-web-app-and-create-a-new-simulation) when running simulator web app.
1. In first run it was showing error environment variable **PCS_IOTHUB_CONNSTRING** not available. This is not described to add for WebService project in lab guide.
1. After adding environment **PCS_IOTHUB_CONNSTRING**. Popup new error in 2nd run environment varible **PCS_STORAGEADAPTER_WEBSERVICE_URL** not available. I added this also.
1. In 3rd run getting another error. 
##Error
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Azure.IoTSolutions.DeviceSimulation.Services

1. And in In Exercise 3 task 5.4, when doing get method for  http://localhost:9003/v1/simulations/1. Then getting status 500 instead of 200.

_Originally posted by @akn9050 in https://github.com/Microsoft/MCW-IoT-for-business/issues/12#issuecomment-444485535_

**Comment by akn9050** [comment]
any update

**Comment by akn9050** [comment]
We are still waiting for update. Please fix the lab end to end and update us on this.

**Comment by Dilini-Perera** [comment]
Hi, 
I have the same issues
Globally, I think there are some instructions missing about how to set some of the environment variables & how to properly deal with the urls/ports

Waiting for the update :) 
Cheers, 
Dilini
Dilini

**Comment by mrfalafel** [comment]
Please try with the March update.
