### ISSUE TITLE
Issue while running hand on lab

### ISSUE THREAD

**Issue by GhumanNavneet** [microsoft/MCW-IoT-and-the-Smart-City#22]
In exercise 1, after Remote Monitoring solution is loaded, map is not visible through out the lab. 

In Exercise 4> Task 3> Step 9, we need to open Module.json, but they have mentioned to open manifest.json which is not available. Can you please update it.

Not even able to sign in docker with the given command. Getting below error:
The system cannot find the file specified. This error may also indicate that the docker daemon is not running

**Comment by DawnmarieDesJardins** [comment]
@mrfalafel 
Hi Lino, please review/advise.
Thanks, Dawnmarie

**Comment by GhumanNavneet** [comment]
Please response as soon as possible.

**Comment by joelhulen** [comment]
I'm going through the lab right now. I'll let you know.

**Comment by joelhulen** [comment]
Regarding your first issue in Exercise 1 where the map is not displaying, it is for me. I just set up a new Remote Monitoring solution and am viewing in Edge on Windows 10.

![image](https://user-images.githubusercontent.com/5950304/57478522-1f134580-7269-11e9-9902-660b7e0fb541.png)

If you go to your browser's developer tools, do you see any errors in the console?

**Comment by joelhulen** [comment]
Exercise 4> Task 3> Step 9 has been updated to reference `module.json`.

I am not seeing the Docker error you are having. When do you see that? In Exercise 4> Task 3> Step 10?

It runs successfully for me. Are you running the lab in the provided VM that was set up in the Before the Hands-on Lab instructions? If not, then you need to double-check your local Docker install.

**Comment by joelhulen** [comment]
@GhumanNavneet I've successfully completed the lab end-to-end on a fresh VM. I did not encounter the same errors as you.

In the meantime, I committed some changes to the lab to clarify things, fix formatting, etc. Also, I merged a PR that updates Cosmos DB "collections" to "containers", updates the reference to module.json (as you pointed out), and removes completed code from the starter projects.

Please reply to my questions above so I can troubleshoot further with you.

**Comment by DawnmarieDesJardins** [comment]
@GhumanNavneet 
Hello!  Are you still having trouble with the lab or may we close this issue as complete?
Thanks, Dawnmarie

**Comment by DawnmarieDesJardins** [comment]
@GhumanNavneet 
Closing issue as resolved.  Please reopen if you are still getting an error.
Thanks, Dawnmarie
