### ISSUE TITLE
September 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-IoT-and-the-Smart-City#29]
This MCW is scheduled for content update.
Solliance - please review current content, open issues #25 , #26 , #27 , #28 and recommended updates for SME review.

**Comment by mrfalafel** [comment]
I can't see any of the vulnerabilities that you reported yesterday (August 15th). can you please let me know where I can see these?
Thanks!

**Comment by DawnmarieDesJardins** [comment]
Hello!
I've copy/pasted the vulnerability information into the issues I mentioned above.  You should have everything there.  Thank you!

**Comment by TheTrainingBoss** [comment]
Thank you!  Please work with Tim Henning at Solliance as I was not assigned to this project for the update. @timahenning

**Comment by mrfalafel** [comment]
Thank you! Please work with Tim Henning at Solliance as I was not assigned to this project for the update. @timahenning

**Comment by DawnmarieDesJardins** [comment]
@mrfalafel 
Thanks Lino!

**Comment by DawnmarieDesJardins** [comment]
Closing as addressed in PR #32
