### ISSUE TITLE
Lab VM Provisioning Error

### ISSUE THREAD

**Issue by jrangama** [microsoft/MCW-IoT-and-the-Smart-City#35]
Anyone has witnessed this error while provisioning the LAB VM?

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'InstallLabVMApps'. Error message: \\\"Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (404) Not Found.\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete - PR merged to fix.
