### ISSUE TITLE
Broken Link "Deploy to Azure" for LABVM

### ISSUE THREAD

**Issue by jrangama** [microsoft/MCW-IoT-and-the-Smart-City#36]
Below link doesn't work with the Deploy to Azure button.

https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fcodingbandit%2FMCW-IoT-and-the-Smart-City%2Ffeature%2Fseptember-2019-update%2FHands-on%2520lab%2FLab-files%2FLabVM%2Fazure-deploy.json

Below is the error message.
There was an error loading the template from URI 'https://raw.githubusercontent.com/codingbandit/MCW-IoT-and-the-Smart-City/feature/september-2019-update/Hands-on lab/Lab-files/LabVM/azure-deploy.json'. Ensure that the template is publicly accessible and does not have any comments.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete - PR merged to fix.
