### ISSUE TITLE
Change Auth provider

### ISSUE THREAD

**Issue by ravitola** [microsoft/MCW-IoT-and-the-Smart-City#38]
All
By default the Azure Remote Monitoring IoT uses the the Active Directory of the Azure subscriber.   I'd like to change this to use a separate Azure AD B2C. directory.  

Is there a doc that documents the steps or changes to the auth service to switch to another OAUTH provider.   Would the react web app also need changes.

**Comment by codingbandit** [comment]
Hi @ravitola - The source code repository for the Azure IoT Remote Monitoring accelerator can be found here:  https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet

The default behavior is to use the Active Directory of the subscriber, and I am unaware of any additional options for this. 

For your scenario, it makes sense to [open an issue within the Azure IoT Remote Monitoring Accelerator repository.](https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/issues)

**Comment by timahenning** [comment]
The author provided a response.  Let us know if you have additional questions.
