### ISSUE TITLE
Getting issue when running Storage Adapter Project

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-IoT-and-the-Smart-City#39]
Getting issue when running Storage Adapter Project in [Exercise 3 Task 4](https://github.com/microsoft/MCW-IoT-and-the-Smart-City/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20IoT%20and%20the%20Smart%20City.md/#task-4-configure-and-run-the-storage-adapter-project).
Getting Below error:
This localhost page can’t be foundNo webpage was found for the web address: http://localhost:9022/v1/status
![image](https://user-images.githubusercontent.com/27498287/69542984-a086b700-0fb2-11ea-8fa4-f436169d1648.png)

**Comment by akn9050** [comment]
I think need to update the lab files, looks like lab file is missing.

**Comment by DawnmarieDesJardins** [comment]
Closing with latest merge - thank you!
