### ISSUE TITLE
Update steps in Exercise 3 task 1 and task 4, otherwise lab users will miss to add App URL

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-IoT-and-the-Smart-City#41]
Update steps in Exercise 3 task 1.5 and task 4.6 under webservice project and then debug, otherwise lab users will miss to add App URL.

Please update the instruction to add App URL under web server settings in debug, default app url doesn't work when running local host.

![image](https://user-images.githubusercontent.com/27498287/69800788-ea161280-11fb-11ea-88b2-aea7cad7d8f8.png)

**Comment by codingbandit** [comment]
Hi @akn9050 ,

In the Simulation project we are only interacting with it via postman and not the browser. This value can actually be set to any URL and not affect the behavior of the lab. It will always be listening on localhost port 9022.

**Comment by codingbandit** [comment]
In the storage adapter project, it specifies to manually open a browser to a URL. No browser is launched automatically.

**Comment by DawnmarieDesJardins** [comment]
@akn9050 
Hi Amit,
We just pushed through a PR that addresses previous issues and Carey has answered your question here.  I'm closing out this issue as resolved.  Please reopen if you're still having trouble.
Dawnmarie

**Comment by Olaowo5** [comment]
this issue is till occurring now, why close it if your not going to fix it

**Comment by timahenning** [comment]
@Olaowo5 if you are experience this issue, you need to provide the exact error message and screenshots on our machine.  This helps determine the problem faster.  

Thanks!

**Comment by Olaowo5** [comment]
@tim The issue that you need to manual type it in otherwise or you get errors

**Comment by codingbandit** [comment]
Dear @Olaowo5 , I hope today finds you well. 

I ran through each step of the hands on lab and ensured each step was documented appropriately.  I have confirmed that if each step is taken, no errors will arise. 

I think the item that is being skipped over in your case is setting the appropriate startup item on the projects. The exact steps are Exercise 3, Task 1, Step 4 (for the device-simulator project) and Exercise 3, Task 4, Step 4 (for the storage-adapter project).

![image](https://user-images.githubusercontent.com/3979478/96172061-d0ed8180-0ef3-11eb-90c5-0414b2c73eb2.png)

Please find a video here (note it will display that the database is already created as I had already ran through the steps once to try and recreate your issue - so this is a subsequent run):

https://www.dropbox.com/s/tj4xrdyzer2du1i/iot-ss.mp4?dl=0
