### ISSUE TITLE
Issue when sending post request to http://localhost:9003/v1/simulations

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-IoT-and-the-Smart-City#42]
I am not getting the correct output when running simulation project in [Exercise 3 Task 5](https://github.com/microsoft/MCW-IoT-and-the-Smart-City/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20IoT%20and%20the%20Smart%20City.md/#task-5-run-the-simulator-web-service-and-create-a-new-simulation) 
Here is the console output when running simmulation project: it is showing lots of environment variables are missing. 
[simmulation project console output.txt](https://github.com/microsoft/MCW-IoT-and-the-Smart-City/files/3901518/simmulation.project.console.output.txt)

Here is the postman screenshot when running post request to http://localhost:9003/v1/simulations
![Snag_9d422d](https://user-images.githubusercontent.com/27498287/69804635-066a7d00-1205-11ea-8961-67b513664bbd.png)

![Snag_a07bcd](https://user-images.githubusercontent.com/27498287/69804884-84c71f00-1205-11ea-91fe-d653641f039f.png)

Can you please Re-validate the lab and fix whatever needs to be fixed. After you fixed issue with Storage adapter, now i am getting error after that while running the device simulation project

**Comment by codingbandit** [comment]
Hi @akn9050,

The errors in the console are for optional placeholders and will not affect the running of the lab itself. Unfortunately new behaviors in Visual Studio made the change to how environment variables are setup and will not persist them through changing the startup item. Instead of having lab users input a bunch more variables, I will issue a pull request that will suppress these warning messages.

**Comment by codingbandit** [comment]
As for your POST request, ensure you do step 5a and 5b - there should only be the one header for content type, from your screenshot it looks as if you have 8 headers set.

**Comment by timahenning** [comment]
Closing this issue.  Please let us know if you have additional questions.

**Comment by Olaowo5** [comment]
this issue is not fixed
