### ISSUE TITLE
Feedback: IoT and the SmartCity

### ISSUE THREAD

**Issue by femi-san** [microsoft/MCW-IoT-and-the-Smart-City#45]
![image](https://user-images.githubusercontent.com/33995485/70732236-f58b3280-1cff-11ea-92aa-e0f19fbe4fe6.png)

![image](https://user-images.githubusercontent.com/33995485/70732279-0c318980-1d00-11ea-9133-6d886daace80.png)

**Comment by timahenning** [comment]
@femi-san Thank you for your detailed suggestions and observations. We will review these items and look into incorporate them into the next update in January 2020.

**Comment by DawnmarieDesJardins** [comment]
Closing this issue as resolved with merge of PR #50
