### ISSUE TITLE
Visual Studio Extension no longer needed in VS 2019

### ISSUE THREAD

**Issue by TheTrainingBoss** [microsoft/MCW-IoT-and-the-Smart-City#49]
In the requirements of the Step by Step md file it mentions that you need to install the following:

> Azure development workload for Visual Studio 2019
> https://docs.microsoft.com/azure/azure-functions/functions-develop-vs#prerequisites

That is not possible as VS 2019 no longer offers that extension as it is built in, so please remove this requirement from the md file.

VS 2017 needs this step to install the extension but not VS 2019
-Lino

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #50
