### ISSUE TITLE
Security Alerts - for next review

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-IoT-and-the-Smart-City#51]
GitHub security alerts, closed as acceptable risk to project for now, please review and incorporate into next test/fix or update.

![Annotation 2020-04-06 113138](https://user-images.githubusercontent.com/39317565/78592886-9abf9e80-77fa-11ea-8a62-aec4c783b11c.png)

**Comment by codingbandit** [comment]
These files no longer exist in the repository - it's safe to close this one out.
