### ISSUE TITLE
Need to move back to .NET Core 2.1 for storage adapter project as 2.2 is not supported …

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-IoT-and-the-Smart-City#52]
Need to move back to .NET Core 2.1 for storage adapter project as 2.2 is not supported anymore

**Comment by akn9050** [comment]
Also, in [Exercise 3:Task 5: Run the Simulator web service and create a new simulation](https://github.com/microsoft/MCW-IoT-and-the-Smart-City/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20IoT%20and%20the%20Smart%20City.md#task-5-run-the-simulator-web-service-and-create-a-new-simulation) 

Application is not starting because of  .net core 2.2 not available and when i changed the target framwork to 2.1 from 2.2 in project file it did not work in simulator app project, but it worked in storage adapter project.

![image](https://user-images.githubusercontent.com/27498287/79596558-67381a80-80fe-11ea-902e-d6af82e28917.png)

**Comment by akn9050** [comment]
@codingbandit , @timahenning  any update on these

**Comment by timahenning** [comment]
Thank you for reporting this issue.  We are working to resolve your issue within the support time frame defined in https://microsoftcloudworkshop.com/.

Tim

**Comment by DawnmarieDesJardins** [comment]
Closing issue as complete with merge of PR #53
