### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by codingbandit** [microsoft/MCW-IoT-and-the-Smart-City#56]
Major requested shift:

Move away from solution accelerator and shift to IoT Central. 

Benefits are as follows:

- remove many of the moving parts, this will simplify the MCW significantly and increase success with students. Most of the issues experienced are with the simulation infrastructure projects, so expected lower rate of issues as IoT Central provides simulation out of the box with the definition of a device template.

- take advantage of IoT Central alerts (can tie in to Microsoft Power Automate), jobs, edge module deployment, analytics, etc.

This shift will impact most of the content of the lab. Instead of using we would use the IoT Central interface. For external to IoT Central functionality we would move to Continuous Data Export feed(s) provided by IoT Central.

Impact:

Abstract and learning objectives - minor update, swap out IoT Remote Monitoring Accelerator with IoT Central.

Overview - needs updated to reflect IoT Central architecture

Architecture - diagram will be greatly simplified, IoT Hub, ASA (on azure side), removal of the Azure Function for reading incoming telemetry (will be replaced by functionality in IoT Central), continuous data export to Event Hub (for Time Series Insights)

Exercise 1 - completely replace.  Removing IoT Remote Monitoring Solution with provisioning IoT Central

Exercise 2 - Remove Task 3 - will not need consumer groups on IoT Hub, Task 4: modify to use event hub as event source for TSI (sink for continuous data export)

Exercise 3 - Completely replace. Cover Device Templates, automated simulation. Write a much simpler "Real" device simulator for traffic light and bus devices. This will eliminate using the accelerator services for the simulator services, storage adapter project etc. (these were copied and modified directly from the remote monitoring accelerator GitHub). Cover device groups, jobs, cloud to device messages, rules, alerts in IOTC, setting up a dashboard with a map (or 3 :D).

Exercise 4 - Replace all IoT Hub tasks with those in IOTC, will have minor changes to IoT Edge module for vehicle telemetry (ex. instructions to get device connection string). All guidance around creating the container, and uploading it to the registry remains. IoT Edge module guidance changes where routing is concerned, and deployment is done through IOTC instead of IOT Hub.

Exercise 5 - completely replace with IOTC sending alerts to the Service Bus Queue through Azure Logic App, or Power Automate

Exercise 6 - No impact

Exercise 7 - same as Exercise 5 impact but with cosmos db.

Exercise 8 - add visualization to IOTC

Exercise 9 - completely replace with Tags/groups in IOTC

Exercise 10 / 11 - should be minimal impact, but will need tested.

After the hands-on-lab updated to remove the IOTC resource group.

**Comment by Teodelas** [comment]
My only feedback is that IoTC is targeted at use cases where custom development is not desired and a managed offering is preferred.  If the goal of this workshop is to increase developer skills, not sure IoTC is he right approach for that as IoTC does not yet provide a broad developer story.

**Comment by codingbandit** [comment]
@Teodelas - There is still developer skills in the mix when it comes to reading off the service bus queue, azure functions triggering off of the queue to send messages to Cosmos DB, and the coding of the command-line based edge module (vehicle telemetry simulator) piece that will run in a Linux vm. The coding area being reduced is that pulled from the accelerator services ([github code](https://github.com/Azure/remote-monitoring-services-dotnet/tree/a864a3ce0fcb3d378635b9f5d1ef90822e3a383f)) only - everything else will remain intact.

**Comment by DawnmarieDesJardins** [comment]
Closing the June 2020 update issue.  This will now be a June 2020 test/fix.
