### ISSUE TITLE
Not able to find Azure Blob Storage on IoT Edge

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-IoT-and-the-Smart-City#61]
In Exercise 4, Task 5, Step16 when  adding Azure Blob Storage on IoT Edge it says no items found

![ex4task5](https://user-images.githubusercontent.com/66515706/97482875-bea42680-197c-11eb-9e31-423f1543f3ad.png)

**Comment by joelhulen** [comment]
It looks like that module was removed from the marketplace. Please try the following and let me know if it works:

1. Add a new **IoT Edge Module**.
2. Name it **AzureBlobStorageonIoTEdge**.
3. Set the Image URI to `mcr.microsoft.com/azure-blob-storage:latest`.
    
    ![image](https://user-images.githubusercontent.com/5950304/97505121-ac12f880-194e-11eb-9edc-b9119b550e36.png)

4. Do NOT enter any environment variables.
5. Paste the following into **Container Create Options**:

```json
{
  "Env":[
    "LOCAL_STORAGE_ACCOUNT_NAME=edgestorage",
    "LOCAL_STORAGE_ACCOUNT_KEY=pM8cWFj0L8h+VKRfE8Fy3tVVtdfOR4bCIzX8N/sDiK1X0znhu8iatFwVfjzwjedDKe5ln+2cI7wpy+2eO1vvQQ=="
  ],
  "HostConfig":{
    "Binds":[
        "/storage/containerdata:/blobroot"
    ],
    "PortBindings":{
      "11002/tcp":[{"HostPort":"11002"}]
    }
  }
}
```

![image](https://user-images.githubusercontent.com/5950304/97505210-dd8bc400-194e-11eb-91ab-083213f3e6ee.png)

**Comment by codingbandit** [comment]
Thanks @joelhulen 

I'm not really sure what's going on - it is still listed as a module (https://azuremarketplace.microsoft.com/en-us/marketplace/apps/azure-blob-storage.edge-azure-blob-storage?tab=Overview) but it's not available when searching the marketplace from within the IoT Hub screens. We'll need to find out if this is going to be some new type of flow to the user interface, or if there is a problem right now with searching the marketplace from within the IoT Hub screens in Azure.

**Comment by codingbandit** [comment]
Update Saturday November 7th. In running through the MCW today - I found they had re-added Azure Blob Storage on IoT Edge back into the marketplace as specified in the lab. I am closing this issue as a result.
