### ISSUE TITLE
Issue in Exercise4

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-IoT-and-the-Smart-City#62]
I was able to complete Exercise 5 and 6. 

![ex6](https://user-images.githubusercontent.com/66515706/97536430-22613a80-19e3-11eb-8808-cf4cbd6d234a.png)

But in Exercise 7. I am facing  this issue now

![ex7](https://user-images.githubusercontent.com/66515706/97536991-0f029f00-19e4-11eb-82be-5f4d66c16aae.png)

**Comment by joelhulen** [comment]
@codingbandit can you take a look at this one? I identified and found a workaround for the other issue because we used the lab components for Cloud Core this week. We didn't need this exercise, so I didn't take a look at the issue.

**Comment by codingbandit** [comment]
Definitely, I will look into this one - thanks, Joel :)

**Comment by akn9050** [comment]
@codingbandit did you find time to check on this issue.

Thanks

**Comment by codingbandit** [comment]
Hi @akn9050 - Not yet

**Comment by akn9050** [comment]
Hi @DawnmarieDesJardins 

I also did this lab from beginning and found following issues:
Exercise 4 Task 3, Step 10: Build for Iot image module Image got failed
![image](https://user-images.githubusercontent.com/27498287/98249294-173a7b80-1f9c-11eb-9b77-59e3367fb66e.png)

Exercise 4 Task 5, Step 28: did not show Vehicle telemetry with **sudo iotedge** list inside iot linux vm.
![image](https://user-images.githubusercontent.com/27498287/98249321-1efa2000-1f9c-11eb-8b70-cbf893fa64b0.png)

In Exercise 7 Task 3 step 7: Not getting any trace after saving the function:
![image](https://user-images.githubusercontent.com/27498287/98250494-8369af00-1f9d-11eb-81f8-946fea29a92a.png)

**Comment by DawnmarieDesJardins** [comment]
@codingbandit 
Hi Carey, please see above and advise.

**Comment by codingbandit** [comment]
I will be running through everything as well :)

**Comment by codingbandit** [comment]
I went through the lab and everything seems to be working fine - I streamed the work here -> https://www.twitch.tv/videos/795181311, my microphone was low so if you want audio you'll need to turn it up. The last exercise related to Time Series Insights will need to be updated in the next update cycle (it has changed quite a bit) - but that doesn't affect the functionality of the lab.

**Comment by timahenning** [comment]
Hi @akn9050,

Are there any updates?  We will be closing this issue in a couple of days.  Also, please make sure to put new errors in a different GitHub issues.  It allows us to close resolved issues and track new issues separately.

**Comment by akn9050** [comment]
Hi @timahenning, I did not find time to go over the lab again. Previously, when I tested it multiple times we faced same issue every time, not sure where I went wrong. I will run through once again sometime next week and will keep the lab instance running in case of same issue. For now, you can close the issue, I will raise a new issue if needed.

**Comment by timahenning** [comment]
Hi @akn9050,

Let's do this.  When you have time, run the lab again.  If you run into the same problem, please open a new issue and we will jump right on it.  We might need to log into your environment.  Please keep it running.  Dawnmarie knows how to contact us or we will reach out to you directly using other channels.

Tim
